### ISSUE TITLE
Generate Mesh Report produces false positives

### ISSUE THREAD

**Issue by justinlaughlin** [ctlee/gamer#11]
![image](https://user-images.githubusercontent.com/27717785/51008056-f10e3680-14fe-11e9-9de1-3447d7db5c88.png)

**Comment by ctlee** [comment]
If you click generate mesh report again does it continue to report the zero area faces?

**Comment by justinlaughlin** [comment]
Yes I deleted then remeshed with F, ctrl+T and it still reported 3 zero area faces. 

In the team drive under proj1/ main/mesh/decamilli/singleSpine/..separateSurfaces...blend almost every face of the ER mesh is considered zero area.

**Comment by ctlee** [comment]
Closed by #16
