### ISSUE TITLE
Normal smooth causes faces to "disappear"

### ISSUE THREAD

**Issue by justinlaughlin** [ctlee/gamer#19]
Simplest example to reproduce the effect:
Ctrl+A -> Mesh -> Cube
Ctrl+T (triangulate)
Subdivide ~4,5 times
GAMer smooth tris ~5,10 iterations
GAMer Normal smooth

This results in what seems to be faces disappearing from the mesh. Counts before and after show that no faces have been deleted, so perhaps it is a blender display issue

Example:
![image](https://user-images.githubusercontent.com/27717785/52159116-b65a7280-2654-11e9-9d80-a51f2e271814.png)

Even weirder: Selecting the vertex on the middle triangle and using Ctrl++ to select the 2 ring neighborhood shows that it is still connected to the outer vertices. 
![image](https://user-images.githubusercontent.com/27717785/52159186-6d56ee00-2655-11e9-97ef-f25619335ce0.png)

Also, pre-normal-smooth a cellblender mesh analysis outputs that the mesh is watertight, outward facing normals, manifold. After normal-smooth the same analysis reads that the mesh is watertight, with inward facing normals, and manifold.

Will update if I figure this out... Strange.

**Comment by ctlee** [comment]
Confirming that I can reproduce this behavior. Will investigate further.
