### ISSUE TITLE
numpy interface

### ISSUE THREAD

**Issue by fcollman** [ctlee/gamer#31]
i've been talking with Tom Bartol about using Gamer to do mesh improvements.  I would like to try to integrate it into my existing python toolchain for meshes.  Is there a way to instantiate a SurfaceMesh with a set of vertices and faces, ideally with both of those stored in a numpy array, which has the data as a contiguous array in memory.    

I successfully compiled and linked the existing development branch and python module, but all i see is the individual insert_vertex and insert_face methods, and no bulk methods.  Is that correct?

**Comment by ctlee** [comment]
Thanks for checking out GAMer! We're actually moving towards a new python backend generated using pybind11 (PR #30) and moving away from SWIG. This gives us some more flexibility. Sorry for changing things just as you've configured GAMer. The build process is also cleaned up substantially, at least in theory. 

With respect to the existence of bulk methods, we don't currently have any. We could add a SurfaceMesh instantiation function from arrays. However keep in mind that GAMer is based on CASC which is an object based data structure and each simplex in the mesh is its own object. You'd likely get some benefit from a bulk instantiation method, but less than binding an array directly.

**Comment by fcollman** [comment]
So i appear to have been able to successfully compile the new version and run the smoothing on a mesh.  It's not great because it makes a copy of the data and is very slow for the large meshes i deal with (hundreds of thousands to millions of vertices). 
```Python
import pygamer as g
# mesh = (SOME CODE TO LOAD UP A MESH INTO A TRIMESH OBJECT)
sm = g.surfacemesh.SurfaceMesh()
for v in mesh.vertices:
    sm.addVertex(v[0], v[1], v[2], 1, False)
for f in mesh.faces:
    sm.insertFace([f[0],f[1],f[2]])
sm.smooth()
```
This appears to run, but i'm not sure if its results make sense... so i'd like to now get a mesh back out and into python...

This appears to work for vertices, though its a bit hacky and again duplicates the data.
```
new_verts = np.zeros((sm.nVertices,3), mesh.vertices.dtype)
for i in range(len(new_verts)):
    v = sm.getVertex([i]).data()
    new_verts[i, :] = [v.position[0], v.position[1], v.position[2]]
```
Faces on the other hand have no good way to get the indices onto to the vertices, other than parsing the __repr__, as FaceID only has methods for isValid and data which returns only the marker, selected, and orientation.

**Comment by ctlee** [comment]
We agree that the copy operation is very suboptimal. At some point we opted for an object based data structure to help facilitate the possibility of parallel algorithms in the future. WRT getting the mesh back out into Python, in #34, we've introduced a class method `SurfaceMesh.to_ndarray()` which returns numpy arrays of vertex positions, edge and face indices. Also as per your suggestion, we have added a `{simplex}ID.indices()` function which returns the indices of any simplex.

**Comment by fcollman** [comment]
awesome! thank you.  I got it compiled and working, putting data in and back out of gamer
![image](https://user-images.githubusercontent.com/782341/59448400-e875a100-8db9-11e9-80de-530dfb5ff2de.png)
Here's an example mesh after running through some improvement operations.

I'll be able to use this to optimize different parameterizations of gamer workflows for my use case.

**Comment by ctlee** [comment]
Looking good! Closing this issue for now. We're happy to consider other suggestions or feedback, just open a new issue.
