### ISSUE TITLE
Unable to compile on Windows 10

### ISSUE THREAD

**Issue by TrystanMayfaire** [ctlee/gamer#41]
When compiling in Windows 10, I get the following:

-- Building for: Visual Studio 15 2017
-- No GIT VCS found pulling version from file
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18362.
-- The C compiler identification is MSVC 19.16.27034.0
-- The CXX compiler identification is MSVC 19.16.27034.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- GAMer version: 2.0.4
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18362.
CMake Error at C:/Program Files/CMake/share/cmake-3.12/Modules/ExternalProject.cmake:2324 (message):
  error: could not find git for clone of casclib-populate
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.12/Modules/ExternalProject.cmake:3100 (_ep_add_download_command)
  CMakeLists.txt:13 (ExternalProject_Add)

-- Configuring incomplete, errors occurred!
See also "C:/Users/paulh/OneDrive/Documents/GitHub/gamer/build64/_deps/casclib-subbuild/CMakeFiles/CMakeOutput.log".

CMake Error at C:/Program Files/CMake/share/cmake-3.12/Modules/FetchContent.cmake:786 (message):
  CMake step for casclib failed: 1
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.12/Modules/FetchContent.cmake:889 (__FetchContent_directPopulate)
  libraries/CMakeLists.txt:36 (FetchContent_Populate)

-- Configuring incomplete, errors occurred!
See also "C:/Users/paulh/OneDrive/Documents/GitHub/gamer/build64/CMakeFiles/CMakeOutput.log".

Let me know if you need any additional information.

Thanks!

Paul

**Comment by ctlee** [comment]
Paul, thanks for trying out GAMer! It looks like CMake cannot find `git` on your machine. If `git` is installed it's likely not on your path. If it's not installed, the easiest way to get a copy of `git` is by downloading it here: https://git-scm.com/downloads

**Comment by TrystanMayfaire** [comment]
Chris,

Thanks for the response. I've got git, but I'll double check whether it's
on my PATH and hey back to you tomorrow.

Paul

**Comment by TrystanMayfaire** [comment]
Resolved! I'd reinstalled most of my software on this new machine, but while I installed GitDesktop I forgot to install Git itself. Got everything compiled perfectly. Thanks!

**Comment by ctlee** [comment]
Awesome! Closing this issue. Please feel free to open a new ticket if you have any future questions or feedback.
