### ISSUE TITLE
Feature request: readpdb_distgrid in pygamer

### ISSUE THREAD

**Issue by jrsacher** [ctlee/gamer#58]
I've been looking for something that can generate the SAS as a grid and`readpdb_distgrid` looks promising!

I see that, in the C++ documentation and code (at least `PDBReader.h`), the `readpdb_distgrid` function is listed as `[WIP]`. Is it still a work in progress or is it fully functional?

If it's working, can it be added to the Python API?

Let me know what I can do to help or test things!

Thanks,

Josh

**Comment by ctlee** [comment]
Hi Josh, 

Thanks for your interest! I honestly don't remember why it's labeled as WIP. It's possible that the implementation wasn't as stable as I would have liked. If you want to try it out that would be great.

I have no issue with adding it to the Python API. We could emit a warning to suggest that it's experimental. Perhaps you can send a PR with the addition?

**Comment by jrsacher** [comment]
I'll give it a shot! I know nothing about C++ but I think I figured out where to copy-paste and make changes! 😁

**Comment by jrsacher** [comment]
Addressed in PR #59
